/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswerLog: typeof import('./src/components/AnswerLog.vue')['default']
    AreaCard: typeof import('./src/components/AreaCard.vue')['default']
    Back: typeof import('./src/components/Back.vue')['default']
    Cloud: typeof import('./src/components/Cloud.vue')['default']
    Comic: typeof import('./src/components/Comic.vue')['default']
    CopyPuzzle: typeof import('./src/components/CopyPuzzle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExtremeInput: typeof import('./src/components/puzzleVue/extremeInput.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hint: typeof import('./src/components/Hint.vue')['default']
    Library: typeof import('./src/components/Library.vue')['default']
    Mail: typeof import('./src/components/Mail.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    PortalItem: typeof import('./src/components/PortalItem.vue')['default']
    PuzzleItem: typeof import('./src/components/PuzzleItem.vue')['default']
    PuzzleList: typeof import('./src/components/PuzzleList.vue')['default']
    PuzzleMap: typeof import('./src/components/PuzzleMap.vue')['default']
    PuzzleNav: typeof import('./src/components/PuzzleNav.vue')['default']
    RoleBadge: typeof import('./src/components/RoleBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Solution: typeof import('./src/components/Solution.vue')['default']
    SubmitInput: typeof import('./src/components/SubmitInput.vue')['default']
  }
}
